{
    'name': 'Theme Appeul Travel',
    'description': 'Theme Appeul Travel',
    'category': 'Theme/Services',
    'summary': 'Legal, Corporate, Business, Tech, Services',
    'sequence': 120,
    'version': '2.1.0',
    'author': 'Odoo S.A.',
    'depends': ['theme_common', 'wt_hotel_reservation'],
    'data': [
        # 'data/ir_asset.xml',
        # 'views/image_content.xml',
        # 'views/snippets/s_cover.xml',
        # 'views/snippets/s_carousel.xml',
        # 'views/snippets/s_text_image.xml',
        # 'views/snippets/s_three_columns.xml',
        # 'views/snippets/s_call_to_action.xml',
        # 'views/snippets/s_title.xml',
        # 'views/snippets/s_features.xml',
        # 'views/snippets/s_numbers.xml',
        # 'views/snippets/s_banner.xml',
        # 'views/snippets/s_image_text.xml',
        # 'views/snippets/s_color_blocks_2.xml',
        # 'views/snippets/s_comparisons.xml',
        # 'views/snippets/s_product_catalog.xml',
        # 'views/snippets/s_quotes_carousel.xml',
        'views/snippets/explore-hotels.xml',
        'views/snippets/snippets.xml',
        'views/hotel_info.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            #'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css',
            'theme_clean/static/src/scss/styles.scss',
            'theme_clean/static/src/js/explore-hotels.js',
            'theme_clean/static/src/js/explore-hotels-options.js',
            'theme_clean/static/src/lib/magnific-popup.css',
            'theme_clean/static/src/lib/daterangepicker.css',
            'theme_clean/static/src/lib/slick-theme.css',
            'theme_clean/static/src/lib/slick.css',
            'theme_clean/static/src/lib/jquery.desoslide.css',
            'theme_clean/static/src/lib/owl.carousel.min.css',
            'theme_clean/static/src/lib/animate.min.css',
            'theme_clean/static/src/scss/custom.scss',
            'theme_clean/static/src/lib/lazysizes.min.js',
            'theme_clean/static/src/lib/jquery.magnific-popup.js',
            'theme_clean/static/src/lib/daterangepicker.js',
            'theme_clean/static/src/lib/slick.js',
            'theme_clean/static/src/lib/jquery.desoslide.min.js',
            'theme_clean/static/src/lib/owl.carousel.js',
            'theme_clean/static/src/js/booking_datepicker.js',
            'theme_clean/static/src/js/guestspicker.js',
            'theme_clean/static/src/js/search_bar.js',
            'theme_clean/static/src/js/popover.js',
            'theme_clean/static/src/js/slideshow.js',
            'theme_clean/static/src/js/owl_slider_hotel.js',
            'theme_clean/static/src/js/filter_collapse.js',
            'theme_clean/static/src/js/custom.js'

        ],
        'web._assets_primary_variables': [
            "theme_clean/static/src/scss/primary_variables.scss",
        ],
        # 'website.assets_editor': [
        #     'theme_clean/static/src/js/tour.js',
        # ],
    },

    # 'images': [
    #     'static/description/clean_description.jpg',
    #     'static/description/clean_screenshot.jpg',
    # ],
    # 'images_preview_theme': {
    #     'website.s_cover_default_image': '/theme_clean/static/src/img/backgrounds/bg_snippet_09.jpg',
    #     'website.s_text_image_default_image': '/theme_clean/static/src/img/content/image_content_19.jpg',
    #     'website.s_banner_default_image': '/theme_clean/static/src/img/backgrounds/bg_snippet_07.jpg',
    #     'website.s_carousel_default_image_1': '/theme_clean/static/src/img/content/image_content_25.jpg',
    #     'website.s_three_columns_default_image_1': '/theme_clean/static/src/img/content/image_content_22.jpg',
    #     'website.s_three_columns_default_image_2': '/theme_clean/static/src/img/content/image_content_23.jpg',
    #     'website.s_three_columns_default_image_3': '/theme_clean/static/src/img/content/image_content_24.jpg',
    # },
    # 'snippet_lists': {
    #     'homepage': ['s_cover', 's_text_image', 's_title', 's_features', 's_carousel', 's_numbers',
    #                  's_three_columns', 's_call_to_action'],
    # },
    'license': 'LGPL-3',
    #'live_test_url': 'https://theme-clean.odoo.com',

}
